local colors = require("theme").getCurrentTheme()
local utils = require("core.utils")

if not colors then
	return { error = "colors not found" }
end

return {
	DevIconDefault = { fg = colors.red, bg = colors.background },
	DevIconCsharp = { fg = colors.green, bg = colors.background },
	DevIconC = { fg = colors.blue, bg = colors.background },
	DevIconCpp = { fg = colors.base0C, bg = colors.background },
	DevIconLua = { fg = colors.blue, bg = colors.background },
	DevIcondeb = { fg = utils.mix(colors.foreground, colors.blue, 0.7), bg = colors.background },
	DevIconDockerfile = { fg = utils.mix(colors.foreground, colors.blue, 0.7), bg = colors.background },
	DevIconHtml = { fg = colors.red, bg = colors.background },
	DevIconCSS = { fg = colors.base0C, bg = colors.background },
	DevIconJs = { fg = utils.mix(colors.red, colors.green, 0.5), bg = colors.background },
	DevIconTs = { fg = colors.blue, bg = colors.background },
	DevIconTsx = { fg = colors.base0C, bg = colors.background },
	DevIconJsx = { fg = colors.base0C, bg = colors.background },
	DevIconVue = { fg = colors.green, bg = colors.background },
	DevIconKotlin = { fg = utils.mix(colors.red, colors.blue, 0.5), bg = colors.background },
	DevIconJava = { fg = utils.mix(colors.red, utils.mix(colors.red, colors.green, 0.5), 0.5), bg = colors.background },
	DevIconDart = { fg = utils.mix(colors.foreground, colors.blue, 0.7), bg = colors.background },
	DevIconLock = { fg = colors.red, bg = colors.background },
	DevIconPng = { fg = utils.mix(colors.red, colors.blue, 0.5), bg = colors.background },
	DevIconJpeg = { fg = utils.mix(colors.red, colors.blue, 0.5), bg = colors.background },
	DevIconJpg = { fg = utils.mix(colors.red, colors.blue, 0.5), bg = colors.background },
	DevIconMp3 = { fg = colors.green, bg = colors.background },
	DevIconMp4 = { fg = colors.red, bg = colors.background },
	DevIconPy = { fg = utils.mix(colors.foreground, colors.base0A, 0.7), bg = colors.background },
	DevIconToml = { fg = colors.blue, bg = colors.background },
	DevIconRb = { fg = colors.red, bg = colors.background },
	DevIconrpm = { fg = utils.mix(colors.red, utils.mix(colors.red, colors.green, 0.5), 0.5), bg = colors.background },
	DevIconMd = { fg = colors.blue, bg = colors.background },
	DevIconTrueTypeFont = { fg = colors.foreground, bg = colors.background },
	DevIconOpenTypeFont = { fg = colors.foreground, bg = colors.background },
	DevIconxz = { fg = utils.mix(colors.red, utils.mix(colors.red, colors.green, 0.5), 0.5), bg = colors.background },
	DevIconzip = { fg = utils.mix(colors.red, utils.mix(colors.red, colors.green, 0.5), 0.5), bg = colors.background },
	DevIconZig = { fg = utils.mix(colors.red, utils.mix(colors.red, colors.green, 0.5), 0.5), bg = colors.background },
	DevIconSvelte = { fg = colors.red, bg = colors.background },
	DevIconVim = { fg = colors.green, bg = colors.background },
	DevIconLicense = { fg = utils.mix(colors.red, colors.green, 0.5), bg = colors.background },
	DevIconNix = { fg = colors.blue, bg = colors.background },
	DevIconGitIgnore = { fg = colors.red, bg = colors.background },
	DevIconSh = { fg = colors.green, bg = colors.background },
	DevIconGitlabCI = { fg = colors.red, bg = colors.background },
	DevIconSQL = { fg = colors.base0A, bg = colors.background },
}
